apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: httpd-daemonset
spec:
  selector:
    matchLabels:
      app: httpd-daemon-pod
  template:
    metadata:
      labels:
        app: httpd-daemon-pod
    spec:
      containers:
        - name: httpd-container
          image: httpd
          ports:
          - containerPort: 80
