---

kind: Deployment
metadata:
  name: my-apache
spec:
  replicas: 1
  selector:
    matchLabels:
       app: apache-html
  template:
    metadata:
      labels:
         app: apache-html
    spec:
      containers:
      - name: apache
        image: httpd
        resources:
          requests:
            cpu: 50m
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-apache
spec:
  selector:
    app: apache-html
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
---