apiVersion: v1
kind: Pod
metadata:  
  labels:    
    name: webapp-pod  
  name: webapp-pod
  namespace: default 
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    imagePullPolicy: Always
    name: webapp
    envFrom:
    - secretRef:
       name: db-secret
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-8d28r
      readOnly: true
  restartPolicy: Always
  volumes:
  - name: default-token-8d28r
    secret:
      defaultMode: 420
      secretName: default-token-8d28r