apiVersion: v1
kind: Pod
metadata:
  name: red
  namespace: default
spec:
  containers:
  initContainers:
  - command:
    - sh
    - -c
    - sleep 600
    image: busybox
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: red-container
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-l6xrb
      readOnly: true
  restartPolicy: Always
  volumes:
  - name: default-token-l6xrb
    secret:
      defaultMode: 420
      secretName: default-token-l6xrb