apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-hello
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 3
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-containers
        image: httpd
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
              - cat
              - /usr/local/apache2/htdocs/index.html
          initialDelaySeconds: 30
          timeoutSeconds: 10