apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-hello
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 2
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-containers
        image: httpd
        ports:
        - containerPort: 80