apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: test-aki
spec:
  selector:
    app: httpd-server
  type: NodePort
  ports:
    - name: httpd-port
      port: 80
      targetPort: 80
