apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXljcnAvM2JFNnMvMFNxc0lGWE1qUjJCWVVqQ2Zac29WaWIyWm5LT2k5akFkCnFHazNyVWpjU2pkSnluL3RQSFJNbDBkcjBpTnJjNmhmeFAwNnRaV0wxVmxSVnI0MnRxZ3VJOFpjbU1QdGVlUFEKMEt2MHNRT0FQd2tEOGdnK001dm5JbklIMEVvOVNId1BDcFIwbTBaQmR3Mm1zaVRyVFNpb2RnWE1iczRWZEo0WQptdmJLQ3FKL3BtUEhCdWF4aUhYRzNOOTNaRUVEWS9aNXpEZ0NXV3NNTklHK2E0akUwRVBtdlNQTkt1VFFzYVdDClBPbE5WS3pBREZ3ZzFVSys2amdJaWRCMWZqRlV6bGM5WkN0a1RBdUltUDBXWk5vcFJvUTliU3hVeEVLMnJlQmMKMGdsclZ3Zkw3RHNCcXNBSCt4bUNWTnJyWGZUcFJ6cGFlRlplc1VhZm9RSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBR0haVG1zQXZkNUZYUXVnSGNwS1k5OTIrWGpULy80M216ZkpaTzh3eCticDVFVU5nNGttCk9ZRVlXYjJMcEludVdCMnBDMXBOZFlXOHZra1J5SWgyRUpaQjM3QUl2azc5WVcvckM4blFxVUpGUmxrbnd1Y0kKOTA3U2dTckVTbUxKakZxTy8zbFVSTTFmOGpKQkN6enlDWFZOOW1uZlhidnVrbVVITlA3OWgvYXVkOWFrMm9CagpVUWxla2lFUnVPdmc2UWJlWDNKKzM0cWJ4eXd4UDJ0QkpDcHdCV3ZyT2hCaE82cDZnUENyZGZ4VGJSdmpVb3dZCklFT1lWbU4zeVlWd0hHVFU2ZHFwRTJtcXhweHBXRUFSbTVPQWwwZzQ1WGZqUWIrN21GOFg0WVo2V2dkZU05ckgKSmhzY3R1cjFKR0tHU2xjOUVCNGk0UTNoUmcvTUtBOGxZZDg9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth