apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
spec:
  securityContext: # Pod level
    runAsUser: 1010
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu
    name: ubuntu
    securityContext:
      capabilities:
        add : ["SYS_TIME"]