---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: aki-test
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_root_pwd
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pvc1
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: aki-test
  labels:
    run: mysql-service
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    app: mysql
