---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  hostPath:
    path: "/data"
  accessModes:
  - ReadWriteOnce
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: aki-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi